theme: minima
title: Ryan Tsai's Machine Learning Portfolio
url: https://rfdspeng.github.io/
github: https://github.com/rfdspeng
resume: /assets/pdf/Ryan%20Tsai%20Resume.pdf
linkedin: https://www.linkedin.com/in/ryan-tsai-7a7b353a/

sass:
  style: compressed

#description: ML and AI Portfolio